---
spring:
  flyway:
    password: ${POSTGRESQL_PASSWORD_FLYWAY}
    user: ${POSTGRESQL_USER_FLYWAY}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USER_DATA}
    password: ${POSTGRESQL_PASSWORD_DATA}
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}?ssl=true&sslmode=verify-full&sslrootcert=${SSL_POSTGRES_CERTIFICATE_PATH}&sslcert=${SSL_DISTRIBUTION_CERTIFICATE_PATH}&sslkey=${SSL_DISTRIBUTION_PRIVATE_KEY_PATH}

